// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4CInPVifh6OwrL1UfTIbh67RtWjazaDI',
    appId: '1:88156808956:web:4cb8a87fc6faa7b01fd979',
    messagingSenderId: '88156808956',
    projectId: 'e-commerce-app-322aa',
    authDomain: 'e-commerce-app-322aa.firebaseapp.com',
    storageBucket: 'e-commerce-app-322aa.appspot.com',
    measurementId: 'G-CNE1LPECR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkbH7Ido--P13gSLVAcuEr0CkCjKt9r5U',
    appId: '1:88156808956:android:2e751a3874cf184a1fd979',
    messagingSenderId: '88156808956',
    projectId: 'e-commerce-app-322aa',
    storageBucket: 'e-commerce-app-322aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf_xY8nL_uuOnfHdfHTS0WKSvjdIvh1NE',
    appId: '1:88156808956:ios:43a1c9cf9defffa71fd979',
    messagingSenderId: '88156808956',
    projectId: 'e-commerce-app-322aa',
    storageBucket: 'e-commerce-app-322aa.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf_xY8nL_uuOnfHdfHTS0WKSvjdIvh1NE',
    appId: '1:88156808956:ios:43a1c9cf9defffa71fd979',
    messagingSenderId: '88156808956',
    projectId: 'e-commerce-app-322aa',
    storageBucket: 'e-commerce-app-322aa.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4CInPVifh6OwrL1UfTIbh67RtWjazaDI',
    appId: '1:88156808956:web:5cf4d6e124860b7e1fd979',
    messagingSenderId: '88156808956',
    projectId: 'e-commerce-app-322aa',
    authDomain: 'e-commerce-app-322aa.firebaseapp.com',
    storageBucket: 'e-commerce-app-322aa.appspot.com',
    measurementId: 'G-G4HLXBJNKW',
  );
}
